name: dotnet package

on: [push]

env:
  ConnectionStringMongoDB: ${{ secrets.CONNECTIONSTRINGMONGODB }}
  DiscordToken: ${{ secrets.DISCORDTOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
      # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
           ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.SERVER_URL}}
          username: "pale"
          password: ${{secrets.USER_PASSWORD}}
          protocol: ftps
          port: 22
      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal
