name: dotnet package

on: [push]

env:
  ConnectionStringMongoDB: ${{ secrets.CONNECTIONSTRINGMONGODB }}
  DiscordToken: ${{ secrets.DISCORDTOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
      # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
           ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore #-property:PublishDir=${{env.DOTNET_ROOT}}/prg/
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{secrets.SERVER_URL}}
          username: pale
          password: ${{ secrets.USER_PASSWORD }}
          localDir: ${{env.DOTNET_ROOT}}
      #- name: Upload
        #run: |
         # echo "put -r ./" > sftp_commands.txt
          #sftp -b sftp_commands.txt pale@${{secrets.SERVER_URL}}
        #- run: ${{secrets.USER_PASSWORD}}
        #- run: put -r ./
        #uses: SamKirkland/FTP-Deploy-Action@v3.0.0-patch
        #with:
        #  ftp-server: sftp://${{secrets.SERVER_URL}}
        # ftp-username: "pale"
        #  ftp-password: ${{secrets.USER_PASSWORD}}
          #local-dir: ${{env.DOTNET_ROOT}}/prg/
          #protocol: sftp
          #port: 22
          #dry-run: true
          #timeout: 60000
      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal
